import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen">
          <a className="absolute top-10 right-20" href="mailto:helgihel@gmail.com">Contact</a>
        {children}
      </body>
    </html>
  );
}
